from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field


class JobStatus(str, Enum):
    """Lifecycle states of an asynchronous processing job."""
    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"


class UploadedFileInfo(BaseModel):
    """Metadata representing an uploaded file saved to disk."""
    filename: str
    saved_path: str
    size_bytes: int
    content_type: Optional[str] = None


class FileAnalysisResponse(BaseModel):
    """Structured analysis response returned by Gemini for an uploaded file."""
    modality: str
    summary: str
    key_topics: List[str] = Field(default_factory=list)
    entities: List[str] = Field(default_factory=list)
    suggested_tone: str
    notable_visual_elements: List[str] = Field(default_factory=list)


class HookItem(BaseModel):
    """Social media content hook representation."""
    angle: str
    headline: str
    why_it_works: str


class PlatformCopyResponse(BaseModel):
    """Structured platform copy generated by Gemini."""
    headline: str
    subtext: str
    caption: str
    hashtags: List[str] = Field(default_factory=list)
    cta: str


class PlatformCopyItem(BaseModel):
    """Platform copy variant associating hook angle, platform, and copy payload."""
    model_config = {"protected_namespaces": ()}
    hook_angle: str
    platform: str
    copy: Dict[str, Any]


class RenderItem(BaseModel):
    """Rendered static image representation for a social media post."""
    platform: str
    hook_angle: str
    image_path: str


class CarouselSlideItem(BaseModel):
    """Structured carousel slide content generated by Gemini."""
    slide_number: int
    slide_type: Literal["hook", "content", "cta"]
    title: str
    body: str


class CarouselSlideOutput(BaseModel):
    """Rendered carousel slide image path."""
    slide_number: int
    image_path: str


class CarouselItem(BaseModel):
    """Carousel representation containing rendered slides for a platform and hook."""
    platform: str
    hook_angle: str
    slides: List[Dict[str, Any]]


class JobState(BaseModel):
    """Internal model for in-memory job state tracking."""
    job_id: str
    status: JobStatus = JobStatus.PENDING
    files: List[UploadedFileInfo] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    result: Optional[Any] = None
    error: Optional[str] = None

    def __getitem__(self, item: str) -> Any:
        return getattr(self, item)

    def __setitem__(self, item: str, value: Any) -> None:
        setattr(self, item, value)

    def get(self, item: str, default: Any = None) -> Any:
        return getattr(self, item, default)


class UploadResponse(BaseModel):
    """Response returned upon successfully uploading files."""
    job_id: str
    message: str
    files_count: int
    filenames: List[str]


class JobStatusResponse(BaseModel):
    """Response returned when checking the status of a job."""
    job_id: str
    status: JobStatus
    created_at: datetime
    updated_at: datetime
    files_count: int
    filenames: List[str]
    error: Optional[str] = None


class JobResultResponse(BaseModel):
    """Response returned when requesting the result of a job."""
    job_id: str
    status: JobStatus
    result: Optional[Any] = None
    error: Optional[str] = None
